;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        icicle-goto-marker-or-set-mark-command
        icicle-yank-maybe-completing
        kill-region-or-to-beginning-of-line
        read-only-mode
        smart-beginning-of-line
        wdired-finish-edit
        wdired-next-line
        wdired-previous-line
        ))

(setq mc/cmds-to-run-once
      '(
        ))
