;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-or-skip-quote
        c-electric-delete-forward
        c-indent-line-or-region
        copy-region-or-whole-line
        end-of-buffer
        helm-M-x
        icicle-goto-marker-or-set-mark-command
        icicle-yank-maybe-completing
        indent-for-tab-command
        kill-region-or-to-beginning-of-line
        mouse-set-region
        ns-copy-including-secondary
        read-only-mode
        smart-beginning-of-line
        sp--self-insert-command
        sp-forward-sexp
        wdired-finish-edit
        wdired-next-line
        wdired-previous-line
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-buffer-menu
        ))
