(use-package smartparens
  :diminish smartparens-mode
  :init
  (progn
    (add-to-list 'sp--lisp-modes 'geiser-repl-mode)
    (require 'smartparens-config)
    (smartparens-global-mode t)
    (setq sp-show-pair-delay 0)

    (show-smartparens-global-mode t)
    (defvar my-sp-bindings '(("C-M-f"       . sp-forward-sexp)
                             ("C-M-b"       . sp-backward-sexp)
                             ("C-M-u"       . sp-backward-up-sexp)
                             ("C-M-d"       . sp-down-sexp)
                             ("C-M-n"       . sp-next-sexp)
                             ("C-M-p"       . sp-previous-sexp)
                             ("C-M-a"       . sp-backward-down-sexp)
                             ("C-M-e"       . sp-up-sexp)
                             ("C-S-a"       . sp-beginning-of-sexp)
                             ("C-S-d"       . sp-end-of-sexp)
                             ("C-M-k"       . sp-kill-sexp)
                             ("C-M-w"       . sp-copy-sexp)
                             ("C-M-t"       . sp-transpose-sexp)
                             ("M-D"         . sp-splice-sexp)
                             ("M-<delete>"  . sp-unwrap-sexp)
                             ("C-]"         . sp-select-next-thing-exchange)
                             ("C-M-]"       . sp-select-next-thing)
                             ("M-F"         . sp-forward-symbol)
                             ("M-B"         . sp-backward-symbol)
                             ;; paredit
                             ("C-)"         . sp-forward-slurp-sexp)
                             ("C-("         . sp-backward-slurp-sexp)
                             ("C-}"         . sp-forward-barf-sexp)
                             ("C-{"         . sp-backward-barf-sexp)
                             ("C-<right>"   . sp-forward-slurp-sexp)
                             ("C-M-<left>"  . sp-backward-slurp-sexp)
                             ("C-<left>"    . sp-forward-barf-sexp)
                             ("C-M-<right>" . sp-backward-barf-sexp))
      "My smartparens keybindings.")

    (sp--populate-keymap my-sp-bindings)))
